<?php

/**
 * WP Connector — Endpoint module.
 *
 * Exposes the key-protected REST endpoint at /wp-json/wpconnector/v1/status.
 * Loaded by wpconnector.php when the mode is 'endpoint' or 'both'; the secret
 * key is generated by wpc_ensure_endpoint_key() in the main file (on
 * activation and whenever an endpoint mode is selected).
 */

if (! defined('ABSPATH')) {
	exit;
}

add_action('admin_menu', function () {
	add_options_page('WP Connector Endpoint', 'WP Connector Endpoint', 'manage_options', 'wpconnectorendpoint', 'wpce_settings_page');
});

function wpce_settings_page()
{
	if (isset($_POST['wpce_key']) && check_admin_referer('wpce_save_key')) {
		update_option('wpce_secret_key', sanitize_text_field($_POST['wpce_key']));
	}

	$key      = get_option('wpce_secret_key');
	$endpoint = rest_url('wpconnector/v1/status');
	$endpoint_key = rest_url('wpconnector/v1/status?key=' . $key);
?>
	<div class="wrap">
		<h1>WP Connector Endpoint</h1>
		<p>Endpoint URL: <code><?php echo esc_html($endpoint_key); ?></code></p>
		<p>Secret Key: <code><?php echo esc_html($key); ?></code></p>
		<p>Paste this exact line into WP Connector Hub with the Secret Key provided below</p>

		<form method="post">
			<?php wp_nonce_field('wpce_save_key'); ?>
			<p>
				<label for="wpce_key" style="display:inline-block;width:100px;">Endpoint:</label>
				<code><?php echo esc_html($endpoint); ?></code>
			</p>
			<p>
				<label for="wpce_key" style="display:inline-block;width:100px;">Secret Key:</label>
				<input type="text" id="wpce_key" name="wpce_key" value="<?php echo esc_attr($key); ?>" style="width:320px;">
			</p>
			<p><button type="submit" class="button button-primary">Save</button></p>
		</form>
	</div>
<?php
}

add_action('rest_api_init', function () {
	register_rest_route('wpconnector/v1', '/status', array(
		'methods'             => 'GET',
		'callback'            => 'wpce_status_callback',
		'permission_callback' => 'wpce_permission_check',
	));
});

function wpce_permission_check(WP_REST_Request $request)
{
	$key      = get_option('wpce_secret_key');
	$provided = $request->get_param('key');
	if (! $provided) {
		$provided = $request->get_header('x-wpconnector-key');
	}
	return $key && $provided && hash_equals($key, $provided);
}

/**
 * Whether core background updates are allowed, mirroring core's own decision
 * chain (WP_Automatic_Updater / Core_Upgrader::should_update_to_version):
 * the AUTOMATIC_UPDATER_DISABLED and WP_AUTO_UPDATE_CORE constants, the
 * Updates-screen toggle (the auto_update_core_major option, WP 5.6+) and the
 * allow_*_auto_core_updates filters. Returns 'disabled', 'minor' (maintenance
 * and security releases only — the WP default) or 'all' (major releases too).
 */
function wpce_core_auto_update_policy()
{
	if (defined('AUTOMATIC_UPDATER_DISABLED') && AUTOMATIC_UPDATER_DISABLED) {
		return 'disabled';
	}
	if (apply_filters('automatic_updater_disabled', false)) {
		return 'disabled';
	}

	$minor = true;
	$major = false;
	if (defined('WP_AUTO_UPDATE_CORE')) {
		if (false === WP_AUTO_UPDATE_CORE) {
			$minor = false;
		} elseif (true === WP_AUTO_UPDATE_CORE || in_array(WP_AUTO_UPDATE_CORE, array('beta', 'rc', 'development', 'branch-development'), true)) {
			$major = true;
		}
		// 'minor' keeps the defaults.
	}
	if ('enabled' === get_site_option('auto_update_core_major')) {
		$major = true;
	}

	$minor = apply_filters('allow_minor_auto_core_updates', $minor);
	$major = apply_filters('allow_major_auto_core_updates', $major);

	if ($major) {
		return 'all';
	}
	return $minor ? 'minor' : 'disabled';
}

function wpce_status_callback()
{
	if (! function_exists('get_plugins')) {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
	}
	if (! function_exists('wp_is_auto_update_enabled_for_type')) {
		require_once ABSPATH . 'wp-admin/includes/update.php';
	}

	$all_plugins    = get_plugins();
	$active_plugins = get_option('active_plugins', array());

	// Per-plugin auto-updates: the Plugins-screen toggles store enabled plugin
	// files in the auto_update_plugins option; the whole feature can be turned
	// off site-wide (DISALLOW_FILE_MODS, automatic_updater_disabled, ...).
	$plugin_auto_supported = wp_is_auto_update_enabled_for_type('plugin');
	$plugin_auto_updates   = $plugin_auto_supported ? (array) get_site_option('auto_update_plugins', array()) : array();

	$update_plugins = get_site_transient('update_plugins');
	if (false === $update_plugins) {
		if (! function_exists('wp_update_plugins')) {
			require_once ABSPATH . 'wp-admin/includes/update.php';
		}
		wp_update_plugins();
		$update_plugins = get_site_transient('update_plugins');
	}
	$updates = ! empty($update_plugins->response) ? $update_plugins->response : array();

	$update_core = get_site_transient('update_core');
	if (false === $update_core) {
		if (! function_exists('wp_version_check')) {
			require_once ABSPATH . 'wp-admin/includes/update.php';
		}
		wp_version_check();
		$update_core = get_site_transient('update_core');
	}
	$wp_latest_version   = get_bloginfo('version');
	$wp_update_available = false;
	if (! empty($update_core->updates[0])) {
		$latest = $update_core->updates[0];
		if (isset($latest->current)) {
			$wp_latest_version = $latest->current;
		}
		if (isset($latest->response) && 'latest' !== $latest->response) {
			$wp_update_available = true;
		}
	}

	$plugins_list       = array();
	$plugins_auto_count = 0;
	foreach ($all_plugins as $file => $data) {
		$auto_update = in_array($file, $plugin_auto_updates, true);
		if ($auto_update) {
			$plugins_auto_count++;
		}
		$plugins_list[] = array(
			'name'             => $data['Name'],
			'version'          => $data['Version'],
			'active'           => in_array($file, $active_plugins, true),
			'update_available' => isset($updates[$file]),
			'new_version'      => isset($updates[$file]->new_version) ? $updates[$file]->new_version : null,
			'auto_update'      => $auto_update,
		);
	}

	return array(
		'domain'                        => home_url(),
		'wp_version'                    => get_bloginfo('version'),
		'wp_latest_version'             => $wp_latest_version,
		'wp_update_available'           => $wp_update_available,
		'core_auto_update'              => wpce_core_auto_update_policy(),
		'php_version'                   => phpversion(),
		'plugins_total'                 => count($all_plugins),
		'plugins_active'                => count($active_plugins),
		'plugins_inactive'              => count($all_plugins) - count($active_plugins),
		'plugins_auto_update'           => $plugins_auto_count,
		'plugins_auto_update_supported' => $plugin_auto_supported,
		'plugins'                       => $plugins_list,
		'themes_installed'              => count(wp_get_themes()),
	);
}
