<?php

/**
 * WP Connector — Endpoint module.
 *
 * Exposes the key-protected REST endpoint at /wp-json/wpconnector/v1/status.
 * Loaded by wpconnector.php when the mode is 'endpoint' or 'both'; the secret
 * key is generated by wpc_ensure_endpoint_key() in the main file (on
 * activation and whenever an endpoint mode is selected).
 */

if (! defined('ABSPATH')) {
	exit;
}

add_action('admin_menu', function () {
	add_options_page('WP Connector Endpoint', 'WP Connector Endpoint', 'manage_options', 'wpconnectorendpoint', 'wpce_settings_page');
});

function wpce_settings_page()
{
	if (isset($_POST['wpce_key']) && check_admin_referer('wpce_save_key')) {
		update_option('wpce_secret_key', sanitize_text_field($_POST['wpce_key']));
	}

	$key      = get_option('wpce_secret_key');
	$endpoint = rest_url('wpconnector/v1/status');
	$endpoint_key = rest_url('wpconnector/v1/status?key=' . $key);
?>
	<div class="wrap">
		<h1>WP Connector Endpoint</h1>
		<p>Endpoint URL: <code><?php echo esc_html($endpoint_key); ?></code></p>
		<p>Secret Key: <code><?php echo esc_html($key); ?></code></p>
		<p>Paste this exact line into WP Connector Hub with the Secret Key provided below</p>

		<form method="post">
			<?php wp_nonce_field('wpce_save_key'); ?>
			<p>
				<label for="wpce_key" style="display:inline-block;width:100px;">Endpoint:</label>
				<code><?php echo esc_html($endpoint); ?></code>
			</p>
			<p>
				<label for="wpce_key" style="display:inline-block;width:100px;">Secret Key:</label>
				<input type="text" id="wpce_key" name="wpce_key" value="<?php echo esc_attr($key); ?>" style="width:320px;">
			</p>
			<p><button type="submit" class="button button-primary">Save</button></p>
		</form>
	</div>
<?php
}

add_action('rest_api_init', function () {
	register_rest_route('wpconnector/v1', '/status', array(
		'methods'             => 'GET',
		'callback'            => 'wpce_status_callback',
		'permission_callback' => 'wpce_permission_check',
	));
});

function wpce_permission_check(WP_REST_Request $request)
{
	$key      = get_option('wpce_secret_key');
	$provided = $request->get_param('key');
	if (! $provided) {
		$provided = $request->get_header('x-wpconnector-key');
	}
	return $key && $provided && hash_equals($key, $provided);
}

function wpce_status_callback()
{
	if (! function_exists('get_plugins')) {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
	}

	$all_plugins    = get_plugins();
	$active_plugins = get_option('active_plugins', array());

	$update_plugins = get_site_transient('update_plugins');
	if (false === $update_plugins) {
		if (! function_exists('wp_update_plugins')) {
			require_once ABSPATH . 'wp-admin/includes/update.php';
		}
		wp_update_plugins();
		$update_plugins = get_site_transient('update_plugins');
	}
	$updates = ! empty($update_plugins->response) ? $update_plugins->response : array();

	$update_core = get_site_transient('update_core');
	if (false === $update_core) {
		if (! function_exists('wp_version_check')) {
			require_once ABSPATH . 'wp-admin/includes/update.php';
		}
		wp_version_check();
		$update_core = get_site_transient('update_core');
	}
	$wp_latest_version   = get_bloginfo('version');
	$wp_update_available = false;
	if (! empty($update_core->updates[0])) {
		$latest = $update_core->updates[0];
		if (isset($latest->current)) {
			$wp_latest_version = $latest->current;
		}
		if (isset($latest->response) && 'latest' !== $latest->response) {
			$wp_update_available = true;
		}
	}

	$plugins_list = array();
	foreach ($all_plugins as $file => $data) {
		$plugins_list[] = array(
			'name'             => $data['Name'],
			'version'          => $data['Version'],
			'active'           => in_array($file, $active_plugins, true),
			'update_available' => isset($updates[$file]),
			'new_version'      => isset($updates[$file]->new_version) ? $updates[$file]->new_version : null,
		);
	}

	return array(
		'domain'              => home_url(),
		'wp_version'          => get_bloginfo('version'),
		'wp_latest_version'   => $wp_latest_version,
		'wp_update_available' => $wp_update_available,
		'php_version'         => phpversion(),
		'plugins_total'       => count($all_plugins),
		'plugins_active'      => count($active_plugins),
		'plugins_inactive'    => count($all_plugins) - count($active_plugins),
		'plugins'             => $plugins_list,
		'themes_installed'    => count(wp_get_themes()),
	);
}
