<?php

/**
 * WP Connector — Endpoint module.
 *
 * Bootstraps the endpoint side: the key-protected REST route at
 * /wp-json/wpconnector/v1/status and the Settings > WP Connector Endpoint
 * page. Loaded by wpconnector.php when the mode is 'endpoint' or 'both'; the
 * secret key is generated by wpc_ensure_endpoint_key() in the main file (on
 * activation and whenever an endpoint mode is selected).
 */

if (! defined('ABSPATH')) {
	exit;
}

define('WPCE_PLUGIN_DIR', plugin_dir_path(__FILE__));

require_once WPCE_PLUGIN_DIR . 'includes/class-wpce-settings-page.php';
require_once WPCE_PLUGIN_DIR . 'includes/class-wpce-rest-controller.php';
require_once WPCE_PLUGIN_DIR . 'includes/class-wpce-plugin.php';

$wpce_plugin = new WPCE_Plugin();
$wpce_plugin->init();
